development:
  adapter: postgresql
  encoding: unicode
  database: doitthatway_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: doitthatway_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: doitthatway_production
  pool: 5
